---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/jmhbnz/openshift-gitops-vault-plugin.git'
    targetRevision: HEAD
    path: 3-application