---
# Source: camunda-platform/charts/identity/charts/keycloak/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: camunda-platform-postgresql
  namespace: "camunda"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.2
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  postgres-password: <postgres-password | base64encode>
  password: <password | base64encode>
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
---
# Source: camunda-platform/charts/identity/charts/keycloak/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: camunda-platform-keycloak
  namespace: "camunda"
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-12.3.0
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  admin-password: <admin-password | base64encode>
---
# Source: camunda-platform/charts/identity/templates/connectors-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "camunda-platform-connectors-identity-secret"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: identity
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: identity-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: identity
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  connectors-secret: <connectors-secret | base64encode>
---
# Source: camunda-platform/charts/identity/templates/operate-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "camunda-platform-operate-identity-secret"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: identity
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: identity-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: identity
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  operate-secret: <operate-secret | base64encode>
---
# Source: camunda-platform/charts/identity/templates/optimize-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "camunda-platform-optimize-identity-secret"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: identity
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: identity-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: identity
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  optimize-secret: <optimize-secret | base64encode>
---
# Source: camunda-platform/charts/identity/templates/tasklist-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "camunda-platform-tasklist-identity-secret"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: identity
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: identity-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: identity
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  tasklist-secret: <tasklist-secret | base64encode>
---
# Source: camunda-platform/charts/identity/templates/zeebe-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "camunda-platform-zeebe-identity-secret"
  labels:
    app: camunda-platform
    app.kubernetes.io/name: identity
    app.kubernetes.io/instance: camunda-platform
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: identity-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: identity
  annotations:
    avp.kubernetes.io/path: "camunda-nonprod" # The name of your AWS Secret
type: Opaque
data:
  zeebe-secret: <zeebe-secret | base64encode>