---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camunda
  namespace: argocd
spec:
  destination:
    namespace: camunda
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/chrisfel-dev/gpt-nx-deploy.git'
    targetRevision: HEAD
    path: camunda/overlays/dev/kustomization.yaml