apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
commonLabels:
  environment: dev

resources:
- ../../base
#(Git ignore this file!). This needs to be a secret with the secret backend config per https://argocd-vault-plugin.readthedocs.io/en/stable/backends/
- secret-vault-configuration.yaml
- camunda.yaml
